name: docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        target:
          - tags: zhongruoyu/kalilinux:headless
            platforms: linux/amd64,linux/arm64
            file: headless.Dockerfile
          - tags: zhongruoyu/kalilinux:large
            platforms: linux/amd64,linux/arm64
            file: large.Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: sudo rm -rf /usr/local/lib/android
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          tags: ${{ matrix.target.tags }}
          platforms: ${{ matrix.target.platforms }}
          file: ${{ matrix.target.file }}
          push: true
